// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVQaNiLq6fa-naYsEVAcdit2Cjwglp6eg',
    appId: '1:895377292435:web:bcb54b39069f94eae8a166',
    messagingSenderId: '895377292435',
    projectId: 'safari-82202',
    authDomain: 'safari-82202.firebaseapp.com',
    storageBucket: 'safari-82202.firebasestorage.app',
    measurementId: 'G-4SPMD982GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKilnQjSbrbYSe1-W878HcFR5brXFB1Ps',
    appId: '1:895377292435:android:d852918dc7b2aa5ce8a166',
    messagingSenderId: '895377292435',
    projectId: 'safari-82202',
    storageBucket: 'safari-82202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_OgX4DcnNq00JROBwvD636VuVAPkm6ZM',
    appId: '1:895377292435:ios:97cc257c06e8c139e8a166',
    messagingSenderId: '895377292435',
    projectId: 'safari-82202',
    storageBucket: 'safari-82202.firebasestorage.app',
    iosBundleId: 'com.safari.sma',
  );
}
